### ISSUE TITLE
Configure NATO End Mission for destroying all caches

### ISSUE THREAD

**Issue by thomaslecointre1** [thomaslecointre1/Chernarus_ALiVE_Insurgency.Chernarus#4]
- [x] Each cache will be associated to an array of markers. Markers are destroyed upon cache destruction.

- [x] Mission success for NATO once all caches are blown.

**Comment by thomaslecointre1** [comment]
Cba interfering with handledamage event handler.

**Comment by Hawke442** [comment]
Ammo Box class "AmmoCrates_NoInteractive_Large" was stopping the event handler, change ammo box to default BIS box.
